name: mgl_notes_app
description: Amjil Notes - vertical Mongolian notes app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mongol: ^9.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.3.3
  drift: ^2.30.1
  sqlite3_flutter_libs: ^0.5.41
  mgl_editor_core:
    path: ../mgl-richtext-editor/packages/mgl_editor_core
  mongol_code: ^1.0.5
  archive: ^4.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.1
  build_runner: ^2.10.5

flutter:
  uses-material-design: true

  assets:
    - assets/next.zip
    - assets/fst/dict.bin
    - assets/fst/dict.idx
    - assets/fst/keys.json
    - assets/fst/lists.bin
    - assets/fst/lists.idx
    - assets/fst/words.fst
    - assets/fst/token_table.bin
    - assets/fonts/OyunQaganTig.ttf
    - assets/fonts/OnonSoninSans.ttf

  fonts:
    - family: OyunQaganTig
      fonts:
        - asset: assets/fonts/OyunQaganTig.ttf
