(ns notes-app.services.db
  (:require 
   ["package:cljd_mobile/database/drift/database.dart" :as drift]
   ["package:cljd_mobile/database/electric.dart" :as electric]))
   
(defn db []
  (await (drift/initDriftDatabase)))
  
(def elec (atom nil))

(def auth-token "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTFiYWQ4YS01NDgwLTQ0OWItYmY4Mi05ZmQzMGJjZDI3YjYiLCJleHAiOjE3MjY0OTEyMTIsImlhdCI6MTcxODcxNTQ2MH0.rv0gfie6lVgn9dZxydJaakcR_sfO1P8UX0vPx2SXe-Wxr9yLScws1j2DTiK9aanqHBOgzhLGPrNKDccLyV-oInzgmrzvnSzD2dF6PF44eSrrUNtYLsG0sKKZQw1-wst25Pja_-LD9kh-WWbR3dP6GDtu_lVhVPNpo5xikjPZZ2RNrw8As4PU1tXearoG8B18x6w-nrfSqQCQ6AF_wnvMSNLbdN1bX73MR-UwZQZI2e4cs6cU-rj1gSUQ-GborM2luTJQAuQZntC_jn61AK_quXtIeeIGLyTznmXNXw6TPl6_EiyiWcOgUejbyOSSQGJgw9j83831HH1jh2fOYYYShbVC3BN7WpWt087BhcaHmPliTgClLpR54rywWQy5jzLIVQuHZXKQwJJ7_Waz_SB1tUFJJ9UN8qzYw8PDUzkKZ6ruMrcqHARGYiGFlhRC2swDpM54j3nzT9ztvcDZqMt5b-4oNYZa8OxQG9UP9m7ppDXXSotJH0j5HW8fD8fl-Mv1wFkboOmdPW_IOYoc08QEzbjubMR3MzuwVJdsH-YEYO3nNoojYpI-6xOkdj3Ri7Tc7_TeAc_W2Bl1ApxdeNE90WHG4FgPjHT-Uay5k8MqFBXhB3b61FyPABiDx1UP3rTk3SwcV_Op5o-pTVbRZdu0iMLSZN1OFQwx_JGUmMEpN0E")
  
(defn set-electric []
  (let [d (await (db))
        notes-electric (await (electric/startElectricDrift "notes-app" d))]
    (await (.connect notes-electric auth-token))
    (let [shape (await (.syncTable notes-electric (.-folders d)))]
      (await (.-synced shape)))
    (let [shape (await (.syncTable notes-electric (.-tags d)))]
      (await (.-synced shape)))
    (let [shape (await (.syncTable notes-electric (.-notes d)))]
      (await (.-synced shape)))
    (let [shape (await (.syncTable notes-electric (.-noteTags d)))]
      (await (.-synced shape)))
    (reset! elec notes-electric)))
    