(ns notes-app.utils.router
  (:require
   ["package:flutter/material.dart" :as m]
   [cljd.flutter :as f]))


(defn open-screen [^m/NavigatorState navigator screen]
  (.push navigator
         (#/(m/MaterialPageRoute Object)
          .builder (f/build screen))))
          
(defn open-editor [^m/NavigatorState navigator screen]
  (.push navigator
         (#/(m/MaterialPageRoute Object)
          .builder (f/build screen))))